# Generated by Django 3.2.3 on 2021-06-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_articles',
            new_name='Articles',
        ),
    ]
